version: 0.2

phases:
  install: 
    runtime-versions:
       python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install awscli
      - pip install cfn-lint
      - pip install aws-sam-cli
 build:
  commands:
    - echo Project is being packaged
    - cfn-lint -t template.yml
    - aws cloudformation package --template-file template.yml --s3-bucket cloud-resume-challenge-jaysal --output-template-file packaged-template.yml
    - echo Project is being tested
    - aws lambda invoke --function-name visitorcounter
