name: S3 website upload
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ACCESS_KEY }}
        region: us-east-1
        
    - name: Deploy HTML site to S3 bucket
      run: aws s3 sync ./frontend s3://cloud-resume-challenge-jaysal --delete --acl public-read --follow-symlinks --exclude ".git*/*"
    - name: Invalidate CloudFront Distribution
      run: aws cloudfront create-invalidation --distribution-id GKER342KYTV --paths "/*"
